cc_library(
    name = "single_proto",
    srcs = [
        "single_proto.cpp",
        "single_proto.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//util/zstream",
        "@com_google_protobuf//:protobuf",
    ],
)

cc_library(
    name = "recordio",
    srcs = [
        "recordio.cpp",
        "recordio.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//util/zstream",
        "@com_google_protobuf//:protobuf",
    ],
)
