load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
  name = "service_cc_proto",
  protos = ["service.proto"],
  with_grpc = True,
  visibility = ["//visibility:public"]
)
